### ISSUE TITLE
Add hex sticker

### ISSUE THREAD

**Issue by arthur-shaw** [lsms-worldbank/labeller#17]
Provide a hex sticker. This would (could) be used in a few places:

- README for pizzaz
- adodown documentation site

**Comment by arthur-shaw** [comment]
@kbjarkefur , where do you think we should place this?

- Root of the project
- In a newly created `images` dir?
- Elsewhere?

**Comment by arthur-shaw** [comment]
Here's a hex sticker my wife designed:

![0](https://github.com/lsms-worldbank/labeller/assets/47256431/8568bb8a-781a-4ed5-9231-6c4b11bc1ec0)

**Comment by kbjarkefur** [comment]
> @kbjarkefur , where do you think we should place this?
> 
> * Root of the project
> * In a newly created `images` dir?
> * Elsewhere?

I would vote for `<root>/src/dev/images`. I think only files frequently accessed should get the honor of taking up place on the landing page of the repository. :)

**Comment by kbjarkefur** [comment]
> Here's a hex sticker my wife designed:
> 
> ![0](https://private-user-images.githubusercontent.com/47256431/295640876-8568bb8a-781a-4ed5-9231-6c4b11bc1ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODIwOTgsIm5iZiI6MTcwNDk4MTc5OCwicGF0aCI6Ii80NzI1NjQzMS8yOTU2NDA4NzYtODU2OGJiOGEtNzgxYS00ZWQ1LTkyMzEtNmM0YjExYmMxZWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE0MDMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMzkxNzNiNzhlMTZjOTViOTUwNGEzNTBhZTIyZTdlNzQ2ODFiZjNhYjdhYmFlMGU0YmU5MmIyMGUwYTc2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XPbpV89ErqsomOQNICVk8f2RcNVhVi_JR6CRAwmCXaM)

Fun! I like it.

**Comment by arthur-shaw** [comment]
> I would vote for `<root>/src/dev/images`. I think only files frequently accessed should get the honor of taking up place on the landing page of the repository. :)

I can get onboard with this idea.

A few quick clarifying questions:

- Does `adodown` create `src/dev`?
- Would we want to put the site CSS/SCSS there too?

If we stash both files there, what about something more generic like `assets`?

**Comment by kbjarkefur** [comment]
Yes, to both bullet questions.

Can we renmae the whole folder `dev` to assets? I think that name is confusing as it is a common name for branches in git flow. And everything in the repository is "development" so what is it that is "dev" that should go into this folder?

**Comment by arthur-shaw** [comment]
Alternatively, we can keep both `dev` and `assets`. In my mind, the former might have code for getting started or running common code. To the extent this makes sense, see the `dev` folder for golem projects explained [here](https://engineering-shiny.org/setting-up-for-success.html#setting-things-up-with-dev01_start.r). The contents of the `dev` folder provide a template for creating a project and offer some commands for common actions (e.g., create a module, create functions, etc.)

Meanwhile, still in my mind, `assets` contain web assets (e.g., images/videos, JavaScript, CSS/SCSS, etc.)

**Comment by kbjarkefur** [comment]
Added in 6e0683f5a01f248961506cbd451ba19dc3353d07. hex sticker now on https://lsms-worldbank.github.io/labeller/

**Comment by kbjarkefur** [comment]
I forgot to mark this one complete. But it is complete right?

**Comment by arthur-shaw** [comment]
Yep, it's complete. There's an adodownr [issue to change the path when building the site](https://github.com/lsms-worldbank/adodownr/pull/19) (which, belatedly, needs to be reviewed and merged), but this issue is complete.
